---
title: "mod6"
output: html_document
---

f<-"C:/Users/Audrey/Desktop/countries.csv"
d<-read.csv(f, header = TRUE, sep = ",", stringsAsFactors = FALSE)
head(d)
summary(d)
names(d)
d["country"]
median(d$population, na.rm = TRUE)
#median of the population, use $ to pull out just the population data from the dataset

median(d$area, na.rm = TRUE)
d$density<-(d$population/d$area)
d$density

d <- d[order(-d$density), ]
d[1:10, ]
#(-) before the d$density gives descending order so that greatest density comes first
d <- d[order(d$density), ]
d[1:10, ]
#without the (-) the order function gives ascending order so that least density comes first

d1<-d[order(-d$density), ]
d1[1:20, ]

summary(d1)
median(d1$population, na.rm = TRUE)
median(d1$area, na.rm = TRUE)

new <- d[grep("^[A-F]", d$country), ]
summary(new)
mean(new$population, na.rm = TRUE)
mean(new$area, na.rm = TRUE)

par(mfrow = c(2,3))
#makes panel of 2 rows by 3 columns of the boxplots
boxplot(d$area)
boxplot(log(d$area))

boxplot(d$population)
boxplot(log(d$population))

par(mfrow = c(1,2))
hist(log(d$area,), freq = FALSE, col = "red", main = "PLOT 1", xlab = "(log)area", ylab = "density", ylim = c(0, 0.2))